:rocket: Adding a logout option for the website
redhat-beyond/JobSeeker pull request #103
Opened 2022-04-15 11:45 UTC by amittcohen

Added a logout option, by doing the following steps:
- Updated the urls.py file in the login app to contain a logout option
- Configured a LOGOUT_REDIRECT_URL in the settings.py file
- Updated the logout button link in the base template
- Removed unecessary functions in the views.py file in the login app

2022-04-15 13:45 UTC, paOmer commented
Hi @amittcohen,
I think that removing the login `views.py` file content should be moved to its own PR.

Also, I think it would be clearer to the user, that after login out he would get redirected to one of this 2 options:
- To the main feed
- To a logout template which says to the user he successfully logged out, and there you could add a link to the login page.

2022-04-15 13:45 UTC, paOmer commented
Hi @amittcohen,
I think that removing the login `views.py` file content should be moved to its own PR.

Also, I think it would be clearer to the user, that after login out he would get redirected to one of this 2 options:
- To the main feed
- To a logout template which says to the user he successfully logged out, and there you could add a link to the login page.

2022-04-16 17:08 UTC, amittcohen commented
> Hi @amittcohen, I think that removing the login `views.py` file content should be moved to its own PR.
> 
> Also, I think it would be clearer to the user, that after login out he would get redirected to one of this 2 options:
> 
> * To the main feed
> * To a logout template which says to the user he successfully logged out, and there you could add a link to the login page.

Regarding the views.py file, I have created another pull request (#116 )

2022-04-17 09:51 UTC, Yarboa requested changes
Please add tests,
You could find samples at the Appendix of UI talk
Only login tests i see are those:
https://github.com/redhat-beyond/JobSeeker/blob/main/login/tests.py#L1

There few tests here to verify the login work

2022-05-09 07:35 UTC, paOmer commented on app/settings.py
> +LOGOUT_REDIRECT_URL = '/login/'
I suggest to change it to the feed page url: `/`

Also rebase this PR

2022-05-15 11:55 UTC, paOmer requested changes
Add a test that verify a user gets logged out when trying the logout link

2022-05-17 17:08 UTC, amittcohen commented
@paOmer @Yarboa Added the test

2022-05-17 21:09 UTC, paOmer approved these changes
LGTM

2022-05-17 22:17 UTC, DeanBiton approved these changes

2022-05-18 05:28 UTC, Yarboa approved these changes

2022-05-18 05:29 UTC, merged