🚀  Options Button for Post and Comment
redhat-beyond/JobSeeker pull request #125
Opened 2022-04-19 16:40 UTC by paOmer

Adding an options dropdown button for each post and each comment.
The dropdown will include 'edit' and 'delete' options.
The options will only be visible for the author of the specific comment or post.

The buttons look like the following (top right corner of posts or comments):

<img width="786" alt="Screen Shot 2022-04-19 at 19 35 27" src="https://user-images.githubusercontent.com/99258236/164052560-2d6df072-cdc3-43e8-923c-9fc86f3a9ded.png">

The dropdown menu looks like:

<img width="714" alt="Screen Shot 2022-04-19 at 19 37 05" src="https://user-images.githubusercontent.com/99258236/164052830-e44fcde0-461c-4cf9-a16e-f24daab02278.png">

The links will get updated once issues #107 #115 will resolve.
Close #124

2022-04-19 17:42 UTC, DeanBiton approved these changes
LGTM

2022-04-20 15:44 UTC, ShirleyFichman approved these changes
LGTM

2022-04-23 06:27 UTC, Yarboa requested changes
@paOmer Please suggest how to test it, please add a test

2022-04-23 09:30 UTC, paOmer commented
> @paOmer Please suggest how to test it, please add a test

Added a link to the relevant tests in the PR description.
Adding it [here](https://github.com/redhat-beyond/JobSeeker/blob/0d0d256a9e529b195c068ac058d236c9f8aa830e/feed/tests/test_feed_views.py#L57-L93) also.

2022-04-27 06:24 UTC, Yarboa commented
> @paOmer Please suggest how to test it, please add a test

Thanks

2022-04-27 06:24 UTC, Yarboa approved these changes

2022-04-27 06:24 UTC, merged