Added a requirement for PR approvals to the contributing file
redhat-beyond/JobSeeker pull request #145
Opened 2022-05-05 13:49 UTC by amittcohen

Updated the contributing.md file with the requirement: each PR must have at least 2 team members approvals in order for it to be merged.
Closes #143

2022-05-09 07:20 UTC, paOmer requested changes
Looks good, just rebase to solve pytest issue

2022-05-09 10:42 UTC, amittcohen commented
Tests resolved

2022-05-09 19:35 UTC, paOmer approved these changes

2022-05-09 23:20 UTC, DeanBiton approved these changes

2022-05-12 05:58 UTC, Yarboa approved these changes

2022-05-12 05:58 UTC, merged