🚀 Job Board: Adding the search engine to the job board's view
redhat-beyond/JobSeeker pull request #147
Opened 2022-05-07 21:23 UTC by DeanBiton

- tests in the main branch that relates to this PR:
https://github.com/redhat-beyond/JobSeeker/blob/main/job_board/tests/test_search_view.py

close #146

2022-05-08 15:23 UTC, paOmer approved these changes

2022-05-15 14:54 UTC, kasemAlem requested changes
cannot see tests

2022-05-15 14:56 UTC, DeanBiton commented
> cannot see tests

@kasemAlem this PR implements a different PR that was already tested. 
The link to the tests is written in the description.

2022-05-15 15:08 UTC, kasemAlem commented
Merged

2022-05-15 15:13 UTC, merged