Feed logic tests
redhat-beyond/JobSeeker pull request #87
Opened 2022-04-11 20:59 UTC by DeanBiton

Added tests to check main feed function.

Tests aim to check:
- The main feed function returns a QuerySet
- Each element in the QuerySet is a Post
- Each post in the QuerySet compared to the data migration posts

Please notice that the first 2 commits are from an earlier PR.
Dependes on #64
Close #86

2022-04-11 21:06 UTC, paOmer approved these changes

2022-04-12 06:16 UTC, Yarboa requested changes
see generic comment above

2022-04-12 06:16 UTC, Yarboa commented on feed/tests/test_comment_model.py
> +@pytest.mark.django_db
Please consult with @paOmer about how to treat the tests and fixtures
see this as reference tests #64

2022-04-13 08:52 UTC, Yarboa approved these changes
LGTM

2022-04-14 09:53 UTC, ShirleyFichman approved these changes
Great small PR, LGTM

2022-04-14 11:56 UTC, merged